version: 0.2

phases:
  install:
    commands:
      - echo Installing app dependencies...
      - curl -LO https://dl.k8s.io/release/v1.27.2/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --short --client
    
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 069279771141.dkr.ecr.us-east-2.amazonaws.com
      - IMAGE_REPO_NAME=581355710136.dkr.ecr.us-east-2.amazonaws.com/eks-repo
      - IMAGE_TAG=v1.0.0.RELEASE
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build --tag $IMAGE_REPO_NAME:$IMAGE_TAG .
 

      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - aws eks update-kubeconfig --name my-cluster-micro --region us-east-2
      - echo Push the latest image to cluster
       # Get AWS Credential using STS Assume Role for kubectl
      - echo "Setting Environment Variables related to AWS CLI for Kube Config Setup"          
      - export AWS_ACCESS_KEY_ID="$(aws configure get aws_access_key_id)"
      - export AWS_SECRET_ACCESS_KEY="$(aws configure get aws_secret_access_key)"
      - export AWS_DEFAULT_REGION="$(aws configure get region)"
      - kubectl apply -f deployment.yml
